
# .github/workflows/process-video.yml
name: YouTube Clipper Bot

on:
  repository_dispatch:
    types: [process-video]
  workflow_dispatch:
    inputs:
      youtube_url:
        description: 'YouTube URL to process'
        required: true
        type: string
      chat_id:
        description: 'Telegram Chat ID'
        required: true
        type: string

jobs:
  process-video:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
    
    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Process YouTube video
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        HF_API_TOKEN: ${{ secrets.HF_API_TOKEN }}
        YOUTUBE_URL: ${{ github.event.client_payload.youtube_url || github.event.inputs.youtube_url }}
        CHAT_ID: ${{ github.event.client_payload.chat_id || github.event.inputs.chat_id }}
      run: |
        python src/main.py
    
    - name: Upload artifacts on failure
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: debug-logs
        path: |
          *.log
          temp/
        retention-days: 1

---

# .github/workflows/webhook-handler.yml  
name: Telegram Webhook Handler

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  setup-webhook:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        pip install requests python-telegram-bot
    
    - name: Setup Telegram Webhook
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPO: ${{ github.repository }}
      run: |
        python src/setup_webhook.py

---

# requirements.txt content
requests==2.31.0
python-telegram-bot==20.7
yt-dlp==2023.12.30
youtube-transcript-api==0.6.1
moviepy==1.0.3
pillow==10.1.0
python-dotenv==1.0.0
